$$ BASICS \  OF \  TENSORFLOW \ VERSION \ 2$$
----
---
---

In [1]:
import tensorflow as tf
import numpy as np
import tensorboard

In [2]:
print("TensorFlow version: {}".format(tf.__version__))
print("Keras version: {}".format(tf.keras.__version__))
print("tensorboard version: {}".format(tensorboard.__version__))

TensorFlow version: 2.2.0-dev20200114
Keras version: 2.2.4-tf
tensorboard version: 2.1.0


# Detecting GPU

In [3]:
var = tf.Variable([2,3,4])
if tf.test.is_gpu_available():
    print('running on gpu')
    print(var.device.endswith('GPU:0'))
else:
    print('running on cpu')


W0305 13:31:46.115816 13780 deprecation.py:323] From <ipython-input-3-fbdf60be421c>:2: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


running on cpu


In [4]:
a= np.array([[3, 2.0],[5.0, 4.0]]) 
b=tf.constant([[3, 2.0],[5.0, 4.0]])
print(a)
print("\n")
print(b)

[[3. 2.]
 [5. 4.]]


tf.Tensor(
[[3. 2.]
 [5. 4.]], shape=(2, 2), dtype=float32)


In [5]:

type(a),type(b)

(numpy.ndarray, tensorflow.python.framework.ops.EagerTensor)

In [6]:
# Converts the given value to a Tensor
c=tf.convert_to_tensor(a,dtype=tf.float32)
print(type(c))
print(c)

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[[3. 2.]
 [5. 4.]], shape=(2, 2), dtype=float32)


# Broadcasting Mechanism

In [7]:
# Broadcasting Mechanism
a = tf.range(3)
a=tf.reshape(a,(3,1))
b = tf.range(4)
b=tf.reshape(b,(1,4))
print(a)
print(b)

tf.Tensor(
[[0]
 [1]
 [2]], shape=(3, 1), dtype=int32)
tf.Tensor([[0 1 2 3]], shape=(1, 4), dtype=int32)


In [8]:
c=a+b
c

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])>

In [9]:
type(c)

tensorflow.python.framework.ops.EagerTensor

In [10]:
c[None]

<tf.Tensor: shape=(1, 3, 4), dtype=int32, numpy=
array([[[0, 1, 2, 3],
        [1, 2, 3, 4],
        [2, 3, 4, 5]]])>

In [11]:
c.shape

TensorShape([3, 4])

In [12]:
tf.broadcast_to(b,[3,4])

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])>

In [13]:
tf.broadcast_to(a,[3,4])

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])>

In [14]:
tf.broadcast_to(b,[3,4]) +tf.broadcast_to(a,[3,4])

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])>

In [15]:
d=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
d

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [16]:
#second row
print('all elements of the second row',d[1])
#second column
print('all elements of the second column',d[:,1])
print("element at position M_i,j where  i=2 and j=2 is \n",d[2,2])


all elements of the second row tf.Tensor([4 5 6], shape=(3,), dtype=int32)
all elements of the second column tf.Tensor([2 5 8], shape=(3,), dtype=int32)
element at position M_i,j where  i=2 and j=2 is 
 tf.Tensor(9, shape=(), dtype=int32)


-----
# LINEAR ALGEBRA

-------

An ndarray represents a (possibly multi-dimensional) array of numerical values. With  $ZERO$ axis corresponding to $SCALARS$ $ONE$ axis, an ndarray correspondin gto $VECTORS$. With $two$ axes, an ndarray corresponds to a $MATRIX$.
Arrays with more than two axes do not have special mathematical names, we simply call them $TENSORS$




# SCALARS 
# Scalar (0-D tensors)

## A tensor containing only one element is called a scalar

---
$R$
---


 Formally, we call values consisting of just one numerical quantity scalars. to evaluate the function $f(x)=2x+5$ at $x=2$
 In this equation, each of the terms 2 and 5 scalar values. while x is a placeholders called variable and they represent unknown scalar values.

In [17]:
a=tf.constant([2])
print(a)

tf.Tensor([2], shape=(1,), dtype=int32)



# VECTORS
# Vectors (1-D tensors)


A vector is simply an array of elements.

---
$R^{n}$
---

A VECTOR is a list of scalar values
-----

creating a row vector x containing the first 10 integers starting with 0. Each value in an ndarray is called an element of the ndarray.

In [18]:
x=tf.range(10)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


an element of a vector cab be referenced using a subscript. For example, we can refer to the $i^{th}$
element of x by $x_{i}$.

In coding, we access any element by indexing into the ndarray.

In [19]:
vector=tf.range(9)
vector

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

In [20]:
# first element of the vector
print(vector[0])
# third element of the vector
print(vector[2])

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


# Length, Dimensionality, and Shape

The length of a vector is commonly called the dimension of the vector. To clarify, we use the dimensionality of a vector or an axis to refer to its length, i.e., the number of elements of a vector or an axis. However, we use the dimensionality of an ndarray to refer to the number of axes that an ndarray has. In this sense, the dimensionality of some axis of
an ndarray will be the length of that axis.

In [21]:
len(vector)

9

In [22]:
# We can access an ndarrayʼs shape (the length along each axis) by inspecting its shape property
vector.shape

TensorShape([9])

In [23]:
vector.get_shape()

TensorShape([9])

# MATRICES
# Matrix (2-D tensors)
---
$A=R^{m \times n}$
matrix A consists of m rows and n columns of real-valued scalars

---
Matrices, which are typically denote with bold-faced, capital letters (e.g., X, Y, and Z), are represented in code as ndarrays with 2 axes.

In [24]:
A = tf.range(20)
A=tf.reshape(A,(5, 4))
A

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])>

In [25]:
A[1,2].numpy()# ELEMENT OF THE SECOND ROW AND THIRD COLUMN

6

# TRANSPOSE OF A MATRIX
The transpose of a matrix $A$ is found by exchanging the rows and columns of matrix $A$ and denoted by
$$ A^{T}$$
IF $A=A_{i,j}$ then $A^{T}=A_{j,i}$
if $A=m \times n$ matrix then $A^{T}=n \times m $ 

eg.
Let 
\begin{equation} A=\left|\begin{array}{ccc} 
1 & 2 \\
3 &4
\end{array} \right|\end{equation} then

\begin{equation} A^{T}=\left|\begin{array}{ccc} 
1 & 3 \\
2 &4
\end{array} \right|\end{equation}


In [26]:
a=tf.constant([[1,2],[3,4]])
a


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [27]:
tf.transpose(a)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]])>

# symmetric matrix A
a matrix is symmetric if A = A.⊤
$$A = A^{⊤}$$

In [28]:
B = tf.constant([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 0, 4],
       [3, 4, 5]])>

In [29]:
tf.transpose(B)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 0, 4],
       [3, 4, 5]])>

# Tensors
Just as vectors generalize scalars, and matrices generalize vectors, we can build data structures
with even more axes. Tensors give us a generic way of describing ndarrays with an arbitrary number of axes. Vectors, for example, are first-order tensors, and matrices are second-order tensors

In [30]:
X = tf.range(24)
X=tf.reshape(X,(2, 3, 4))
X

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

In [31]:
X.shape

TensorShape([2, 3, 4])

In [32]:
A= tf.range(24)
A=tf.reshape(A,(2, 3, 4))
B=A#  Assign a copy of A to B by allocating new memory
print(A)
print()
print('--ELEMENTWISE ADDITION OF MATRICES-')
print(B+A)

tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)

--ELEMENTWISE ADDITION OF MATRICES-
tf.Tensor(
[[[ 0  2  4  6]
  [ 8 10 12 14]
  [16 18 20 22]]

 [[24 26 28 30]
  [32 34 36 38]
  [40 42 44 46]]], shape=(2, 3, 4), dtype=int32)


# Hadamard product
elementwise multiplication of two matrices is called their Hadamard product (math notation⊙)

In [88]:
mat=tf.constant([[1,2],[3,4]])
mat
# elementwise multiplication 
mat*mat

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]])>

In [89]:
A= tf.range(24)
A=tf.reshape(A,(6, 4))
B=A#  Assign a copy of A to B by allocating new memory
A

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])>

In [90]:
#ELEMENTWISE MULTIPLICATION
A*B

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361],
       [400, 441, 484, 529]])>

In [91]:
# matrix multiplication 
#  multiplication  of two matrices gives their dot product
tf.matmul(mat,mat)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]])>

# cast(x, dtype, name=None)
 ## Casts a tensor to a new type.

In [92]:
mat=tf.cast(mat,dtype=tf.float32)
mat.dtype
mat

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [93]:
x = tf.range(4)
x, tf.reduce_sum(x)

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=6>)

In [94]:
a=tf.range(4)
a=tf.reshape(a,(2,2))
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3]])>

In [95]:
tf.reduce_sum(a)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [96]:
# Specifying axis=1 will reduce the column dimension (axis 1) by summing up elements of all the columns.
# thus this will sum up all element row-wise
tf.reduce_sum(a,axis=1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 5])>

In [97]:
# to know the total number of elements in an ndarray, i.e., the product of all of the 
# shape elements, we can inspect its size property
tf.size(x).numpy()

4

In [98]:
# identity matrix
tf.eye(2,2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

In [99]:
c.shape

TensorShape([3, 4])

In [100]:
b.shape

TensorShape([2, 2])

In [102]:
a=tf.constant(4)
b=tf.constant(3)
u=tf.divide(a,b)
# exponent
w=tf.pow(a,b)

x=tf.multiply(a,b)

y=tf.add(a,b)

z=tf.subtract(a,b)

# multiplying a by b
print("dividing 4 by 3         -->",u)
#print("finding 4 mod 3         --> ",session.run(v))

print("4 raise to the power 3  -->",w)
print("4 multuply by 3         --> ",x)

print("4 + 3                   -->",y)
print("4 - 3                   --> ",z)
a.get_shape()

dividing 4 by 3         --> tf.Tensor(1.3333333333333333, shape=(), dtype=float64)
4 raise to the power 3  --> tf.Tensor(64, shape=(), dtype=int32)
4 multuply by 3         -->  tf.Tensor(12, shape=(), dtype=int32)
4 + 3                   --> tf.Tensor(7, shape=(), dtype=int32)
4 - 3                   -->  tf.Tensor(1, shape=(), dtype=int32)


TensorShape([])

In [103]:
a=tf.constant(4)
b=tf.constant(3)
total=a+b
total

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [104]:
a = tf.constant([2, 4], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')
# element-wise multiplication
x = tf.multiply(a, b, name='mul')
print(x)

tf.Tensor(
[[ 0  4]
 [ 4 12]], shape=(2, 2), dtype=int32)


In [105]:
tf.size(x)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [106]:
print(a.get_shape())

(2,)


In [107]:
ones=tf.ones_like([[1,3,4],[7,4,8]])
ones

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]])>

In [108]:
f=tf.Variable(26)
f

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=26>

In [109]:
f=f.assign(97)
f

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=97>

In [110]:
# evenly-spaced generated values
tf.linspace(10.0, 13.0, 4)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([10., 11., 12., 13.], dtype=float32)>

In [111]:
tf.linspace(10.0, 13.0, 5)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([10.  , 10.75, 11.5 , 12.25, 13.  ], dtype=float32)>

----
tf.range(start, limit=None, delta=1, dtype=None, name='range')

---

In [112]:
tf.range(0,18,3)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 0,  3,  6,  9, 12, 15])>

In [113]:
nu=tf.range(0,18,3).numpy()
print(nu)
type(nu)

[ 0  3  6  9 12 15]


numpy.ndarray

In [114]:
t = tf.Variable([[4,5,6.],[3.,4,5.]])
t

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[4., 5., 6.],
       [3., 4., 5.]], dtype=float32)>

In [115]:
t.shape

TensorShape([2, 3])

In [116]:
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [117]:
t.get_shape()

TensorShape([2, 3])

In [118]:
t1=tf.range(12)
t1

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])>

In [119]:
tf.rank(t1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

---
## dim column space of A =n rank of A =n

## the rank of a matrix A is the maximum number of linearly independent columns of the matrix and is the same as the number of non-zero eigenvalues of A.

---

In [120]:
t2=tf.Variable([[[1,2,3],[1,1,2]],[[2,2,2],[3,3,3]]])
t2

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[1, 2, 3],
        [1, 1, 2]],

       [[2, 2, 2],
        [3, 3, 3]]])>

In [121]:
tf.rank(t2)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [122]:
t2.shape

TensorShape([2, 2, 3])

In [123]:
x=tf.reshape(t1,[3,4])
x

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [124]:
# converting to numpy array
xx=x.numpy()
print(xx,'\n')

print(type(xx))
print(type(x))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [125]:
tf.rank(x)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [126]:
y=tf.round(tf.random.normal([3,3],-1,1),2)
y

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0., -1., -3.],
       [ 0.,  2., -1.],
       [-1., -2., -1.]], dtype=float32)>

In [127]:
# The generated values follow a uniform distribution
tf.random.uniform([5, 2], -1, 1)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 0.5540645 ,  0.58285785],
       [-0.46140265, -0.6932113 ],
       [-0.41231918, -0.7490363 ],
       [ 0.03512979, -0.1449666 ],
       [ 0.2475574 , -0.5562973 ]], dtype=float32)>

In [128]:
A=tf.Variable([[1,3,0,-1,0],[-1,0,1,1,-1],[0,3,1,0,-1],[2,3,-1,2,1]])
A

<tf.Variable 'Variable:0' shape=(4, 5) dtype=int32, numpy=
array([[ 1,  3,  0, -1,  0],
       [-1,  0,  1,  1, -1],
       [ 0,  3,  1,  0, -1],
       [ 2,  3, -1,  2,  1]])>

In [129]:
# RANK(A)=2
tf.rank(A)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [130]:
t2

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[1, 2, 3],
        [1, 1, 2]],

       [[2, 2, 2],
        [3, 3, 3]]])>

In [131]:
t4=t2[0,0,2]# slice 0, row 1, column 2
t4

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [132]:
t2[1,1,1]# slice 1, row 1, column 2

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [133]:
print(t2[0,0,2].numpy())
print(t2[1,1,2].numpy())

3
3


Find the size (total number of elements) of a tensor
 
    to know the total number of elements in an ndarray
    
    or
    
     the product of all of the shape elements,

In [134]:
tf.size(t2)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [135]:
tf.size(t2).numpy()

12

In [136]:
t2.shape

TensorShape([2, 2, 3])

In [137]:
x

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [138]:
x.dtype

tf.int32

# ragged sensors-- tensors with non-uniform shapes

In [139]:
rag=tf.ragged.constant([[1,2],[],[4],[2,3,4,5]])
rag

<tf.RaggedTensor [[1, 2], [], [4], [2, 3, 4, 5]]>

In [140]:
rag[0],rag[3]

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5])>)

In [141]:
rag.row_lengths

<bound method RaggedTensor.row_lengths of <tf.RaggedTensor [[1, 2], [], [4], [2, 3, 4, 5]]>>

In [142]:
rag.row_lengths(axis=0)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [143]:
rag.row_splits

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([0, 2, 2, 3, 7], dtype=int64)>

In [144]:
a = [3,4,5]
b = 2
tf.math.squared_difference(a,b)#Returns (x - y)(x - y) element-wise

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9])>

In [145]:
tf.reduce_mean(a).numpy(),(tf.reduce_sum(a)/len(a)).numpy()

(4, 4.0)

In [146]:
a1=tf.range(4)
a1=tf.reshape(a1,[2,2])
a1=tf.cast(a1,dtype=tf.float32)
a1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 1.],
       [2., 3.]], dtype=float32)>

In [147]:
## Specifying axis=1 will reduce the column dimension (axis 1) by summing up 
#elements of all the columns.
tf.reduce_sum(input_tensor=a1, axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 5.], dtype=float32)>

In [148]:
# Specifying axis=0 will reduce the row dimension (axis 0) by summing up elements of all the rows thus humming up
# all elements in each column

tf.reduce_sum(input_tensor=a1, axis=0,keepdims=True)

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[2., 4.]], dtype=float32)>

In [149]:
#Find mean across columns (i.e. reduce rows)
tf.reduce_mean(input_tensor=a1, axis=0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [150]:
#Find mean across rows (i.e. reduce columns)
tf.reduce_mean(input_tensor=a1, axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.5, 2.5], dtype=float32)>

In [151]:
tf.random.normal(shape = (3,3), mean=10, stddev=2, dtype=tf.float32)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 9.327534 , 10.866349 , 10.477513 ],
       [ 6.5115547,  6.895667 , 13.244194 ],
       [ 8.216392 , 11.483086 , 13.9130745]], dtype=float32)>

In [152]:
#tf.random.uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)
tf.random.uniform(shape=[2,2],maxval=10)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[9.331103 , 9.496297 ],
       [8.640211 , 5.7898498]], dtype=float32)>

In [153]:
# 1-D tensor
#index            0,   1,  2,  3,   4,   5 , 6,  7,  8,   9          
a = tf.constant([22,  15,  5,  42, 77,  100, 19, -6, -11, 29])

In [154]:
# output the index of the largest value (100 corresponding to index 5)
tf.argmax(a).numpy()

5

In [155]:
# output the index of the smallest value 
tf.argmin(a).numpy()

8

In [156]:
# Returns the indices of a tensor that give its sorted order along an axis
tf.argsort(a)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([8, 7, 2, 1, 6, 0, 9, 3, 4, 5])>

In [157]:
tf.argsort(a,direction='DESCENDING')

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([5, 4, 3, 9, 0, 6, 1, 2, 7, 8])>

In [158]:
a

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 22,  15,   5,  42,  77, 100,  19,  -6, -11,  29])>

In [159]:
a=tf.reshape(a,[-1,2])
a

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[ 22,  15],
       [  5,  42],
       [ 77, 100],
       [ 19,  -6],
       [-11,  29]])>

In [160]:
tf.argsort(a,axis=0,direction='DESCENDING')

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[2, 2],
       [0, 1],
       [3, 4],
       [1, 0],
       [4, 3]])>

In [161]:
a=tf.argsort(a,axis=0,direction='DESCENDING')
a

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[2, 2],
       [0, 1],
       [3, 4],
       [1, 0],
       [4, 3]])>

# Saving and restoring variables

In [162]:
a=tf.Variable([1,2,3,4,5,6,7,7,8])
check_point=tf.train.Checkpoint(var=a)
saved_path=check_point.save('tmp')

In [163]:
check_point.restore(saved_path)
var

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([2, 3, 4])>

In [112]:

f1(x,y).numpy(), f2(x,y).numpy()

(109.0, 109.0)